### ISSUE TITLE
Example given does not work

### ISSUE THREAD

**Issue by matkoniecz** [GIScience/ohsome-py#91]
I created 

```
from ohsome import OhsomeClient

client = OhsomeClient()
wat = client.elements.count.post(bboxes=[8.625,49.3711,8.7334,49.4397],
				      time="2014-01-01",
				      filter="landuse=farmland and type:way")
print(wat)
```

based on https://pypi.org/project/ohsome/

It crashes with

```
Traceback (most recent call last):
  File "/home/mateusz/.local/lib/python3.8/site-packages/ohsome/clients.py", line 285, in _handle_request
    response = self._session().post(url=self._url, data=self._parameters)
  File "/home/mateusz/.local/lib/python3.8/site-packages/ohsome/clients.py", line 64, in _session
    retry_strategy = Retry(
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    wat = client.elements.count.post(bboxes=[8.625,49.3711,8.7334,49.4397],
  File "/home/mateusz/.local/lib/python3.8/site-packages/ohsome/clients.py", line 275, in post
    return self._handle_request()
  File "/home/mateusz/.local/lib/python3.8/site-packages/ohsome/clients.py", line 341, in _handle_request
    return OhsomeResponse(response, url=self._url, params=self._parameters)
UnboundLocalError: local variable 'response' referenced before assignment
```

**Comment by redfrexx** [comment]
I assume this is the same error as #83. I will update the dependencies in pyproject.toml. Maybe this will solve it.
